@startuml design

skinparam Monochrome true

/'
Steps :

1. Load a raw or lossless image (TIFF or PNG)
2. Resize the image (if necessary) and keep the aspect ratio
3. Save the image as JPEG XL (JXL) according to the quality factor and the chroma subsampling
4. Convert the JXL to a lossless format (PNG)
5. Detect the objects in the saved JXL with YOLO
6. Mesure the speed of the detection in seconds
7. Get the predicted classes, the confidence (%) and the actual classes
8. Save the results in a CSV file

Additional features : log everything in case it goes wrong

Things that should be defined :
    The images we want to use
    The weights and the config files to use with YOLO (ex.: yolo and yolo-tiny)

What needs to be done :

Compare the results to the actual classes
Make a good design and integrate everything
'/

class csv.DictWriter {
    __
    + DictWriter(f:io.TextIO, fieldnames:list)
    + writeheader
    + writerow(row:dict)
}

@enduml